version: "3.0"

services:
  grafana:
    container_name: "ni-systemlink-app-tests"
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.6.4}
        grafana_image: ${GRAFANA_IMAGE:-grafana}
    environment:
      - GF_USERS_DEFAULT_THEME=system
    ports:
      - 4000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/ni-systemlink-app
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning

  fake-api:
    container_name: "ni-systemlink-fake-api"
    build:
      context: ./acceptance-tests
    ports:
      - 5000:8080/tcp
